"""Unitary-synthesis tasks: implement an arbitrary target unitary.

Unlike graph-state preparation (one fixed construction rule), a unitary-synthesis
task asks the LLM to find *a* circuit over a universal gate set that realizes a
given target unitary U. Targets are generated by sampling random circuits from
the gate set and taking their unitary, which guarantees realizability and gives
a natural difficulty knob (the generator's gate count).
"""

from dataclasses import dataclass, field
import random

import numpy as np

from circuit import CircuitDefinition, GATE_SETS, _GATE_ARITY, circuit_unitary


@dataclass
class UnitarySynthesisTask:
    """A task to implement `target_unitary` using gates from `gate_set`."""
    num_qubits: int
    target_unitary: np.ndarray  # 2^n x 2^n complex matrix
    gate_set: str = "clifford_t"
    task_id: str = ""
    generator_gate_count: int = 0
    # The circuit used to generate the target (ground truth, never shown to the
    # LLM). Used only for analysis -- e.g. comparing solution length.
    generator_circuit: CircuitDefinition = None

    def __post_init__(self):
        self.target_unitary = np.asarray(self.target_unitary, dtype=complex)
        if not self.task_id:
            h = abs(hash(np.round(self.target_unitary, 6).tobytes())) % (10 ** 8)
            self.task_id = (
                f"u{self.num_qubits}q_{self.gate_set}_"
                f"{self.generator_gate_count}g_{h:08d}"
            )

    # --- Task protocol adapters (see task.py) ---

    def kind(self) -> str:
        return "unitary"

    def gate_set_name(self) -> str:
        return self.gate_set

    def target(self) -> np.ndarray:
        return self.target_unitary

    def structural_features(self) -> dict:
        t_count = 0
        if self.generator_circuit is not None:
            t_count = sum(
                1 for g in self.generator_circuit.gates if g.get("gate") == "T"
            )
        return {
            "num_qubits": self.num_qubits,
            "gate_set": self.gate_set,
            "generator_gate_count": self.generator_gate_count,
            "t_count": t_count,
        }

    def description(self) -> str:
        """Human-readable description for LLM prompts: the target matrix."""
        lines = [
            f"Target {self.num_qubits}-qubit unitary "
            f"(gate set: {self.gate_set}).",
            "Implement the circuit U whose matrix is below. Rows and columns "
            "are indexed by computational basis states |0...0> ... |1...1>.",
            "Matrix entries are given as real+imag:",
        ]
        for row in self.target_unitary:
            cells = [f"{z.real:+.4f}{z.imag:+.4f}j" for z in row]
            lines.append("  [" + ", ".join(cells) + "]")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "kind": "unitary",
            "num_qubits": self.num_qubits,
            "gate_set": self.gate_set,
            "task_id": self.task_id,
            "generator_gate_count": self.generator_gate_count,
            "target_unitary": {
                "real": self.target_unitary.real.tolist(),
                "imag": self.target_unitary.imag.tolist(),
            },
            "generator_circuit": (
                self.generator_circuit.to_dict()
                if self.generator_circuit is not None else None
            ),
        }

    @classmethod
    def from_dict(cls, d: dict) -> "UnitarySynthesisTask":
        u = d["target_unitary"]
        unitary = np.array(u["real"], dtype=complex) + 1j * np.array(u["imag"])
        gen = d.get("generator_circuit")
        return cls(
            num_qubits=d["num_qubits"],
            target_unitary=unitary,
            gate_set=d.get("gate_set", "clifford_t"),
            task_id=d.get("task_id", ""),
            generator_gate_count=d.get("generator_gate_count", 0),
            generator_circuit=(
                CircuitDefinition.from_dict(gen) if gen is not None else None
            ),
        )


def _random_circuit(
    num_qubits: int,
    gate_set: str,
    gate_count: int,
    rng: random.Random,
) -> CircuitDefinition:
    """Sample a random circuit of `gate_count` gates from `gate_set`."""
    gate_names = sorted(GATE_SETS[gate_set])
    gates = []
    for _ in range(gate_count):
        name = rng.choice(gate_names)
        arity = _GATE_ARITY[name]
        qubits = rng.sample(range(num_qubits), arity)
        gates.append({"gate": name, "qubits": qubits})
    return CircuitDefinition(num_qubits=num_qubits, gates=gates)


def generate_unitary_tasks(
    num_tasks: int,
    qubit_range: tuple = (1, 3),
    gate_set: str = "clifford_t",
    gate_count_range: tuple = (2, 6),
    rng: random.Random = None,
) -> list:
    """Generate random unitary-synthesis tasks, deduplicated by target unitary.

    Each target is the unitary of a random circuit drawn from `gate_set`; an
    n-qubit gate set must contain at least one 1-qubit gate for n=1 to work.
    """
    if rng is None:
        rng = random.Random()

    seen = set()
    tasks = []
    attempts = 0
    max_attempts = num_tasks * 200

    while len(tasks) < num_tasks and attempts < max_attempts:
        attempts += 1
        n = rng.randint(qubit_range[0], qubit_range[1])
        # A 2-qubit gate needs >= 2 qubits; cap gate sampling accordingly.
        if n < 2:
            usable = {g for g in GATE_SETS[gate_set] if _GATE_ARITY[g] == 1}
            if not usable:
                continue
        gate_count = rng.randint(gate_count_range[0], gate_count_range[1])
        circuit = _random_circuit(n, gate_set, gate_count, rng)
        unitary = circuit_unitary(circuit)

        key = (n, np.round(unitary, 6).tobytes())
        if key in seen:
            continue
        seen.add(key)

        tasks.append(UnitarySynthesisTask(
            num_qubits=n,
            target_unitary=unitary,
            gate_set=gate_set,
            generator_gate_count=gate_count,
            generator_circuit=circuit,
        ))

    if len(tasks) < num_tasks:
        raise RuntimeError(
            f"Could only generate {len(tasks)}/{num_tasks} unique unitary tasks"
        )
    return tasks


def create_unitary_starter_library(gate_set: str = "clifford_t"):
    """Create a small library of hand-built, verified unitary-synthesis examples."""
    from library import SolvedExample, SolutionLibrary
    from circuit import verify_circuit

    if gate_set != "clifford_t":
        raise ValueError(
            f"No starter library defined for gate set '{gate_set}'"
        )

    specs = [
        (1, [{"gate": "H", "qubits": [0]}],
         "A single Hadamard on qubit 0."),
        (1, [{"gate": "T", "qubits": [0]}],
         "A single T (pi/4 phase) gate on qubit 0."),
        (2, [{"gate": "CNOT", "qubits": [0, 1]}],
         "A single CNOT with control 0, target 1."),
        (2, [{"gate": "H", "qubits": [0]}, {"gate": "CNOT", "qubits": [0, 1]}],
         "Hadamard on qubit 0, then CNOT(0, 1) -- the Bell-state preparation "
         "unitary."),
    ]

    lib = SolutionLibrary()
    for n, gates, explanation in specs:
        circuit = CircuitDefinition(num_qubits=n, gates=gates)
        unitary = circuit_unitary(circuit)
        task = UnitarySynthesisTask(
            num_qubits=n,
            target_unitary=unitary,
            gate_set=gate_set,
            generator_gate_count=len(gates),
            generator_circuit=circuit,
        )
        passed, fidelity = verify_circuit(task, circuit)
        if not passed:
            raise RuntimeError(
                f"Unitary starter example '{task.task_id}' failed "
                f"verification! Fidelity: {fidelity:.6f}"
            )
        lib.add(SolvedExample(
            task=task, explanation=explanation, circuit=circuit,
            fidelity=fidelity,
        ))
    return lib
